name: blake
version: 0.7.0
description: Experimental static site generator for Dart with Markdown support, Jinja templates and live-reload.
repository: https://github.com/vaetas/blake
documentation: https://vaetas.github.io/blake/
homepage: https://vaetas.github.io/blake/

environment:
  sdk: ^3.6.0

executables:
  blake:

dependencies:
  ansicolor: ^2.0.3
  args: ^2.6.0
  file: ^7.0.1
  glob: ^2.1.2
  html: ^0.15.5
  jinja: ^0.6.0
  markdown: ^7.2.2
  meta: ^1.16.0
  mime: ^2.0.0
  path: ^1.9.0
  petitparser: ^6.0.2
  process_run: ^1.2.2+1
  watcher: ^1.1.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  grinder: ^0.9.5
  lints: ^5.1.0
  test: ^1.25.12
