name: blake
version: 0.6.2
description: Experimental static site generator for Dart with Markdown support, Jinja templates and live-reload.
repository: https://github.com/vaetas/blake
documentation: https://vaetas.github.io/blake/
homepage: https://vaetas.github.io/blake/

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  blake:

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  file: ^6.1.2
  glob: ^2.0.1
  html: ^0.15.0
  jinja: ^0.3.4
  markdown: ^4.0.0
  meta: ^1.7.0
  mime: ^1.0.0
  path: ^1.8.0
  petitparser: ^4.3.0
  process_run: ^0.12.2+1
  watcher: ^1.0.0
  xml: ^5.3.0
  yaml: ^3.1.0

dev_dependencies:
  grinder: ^0.9.0
  lints: ^1.0.1
  test: ^1.17.12
